mysql:
  image: mysql:5.7
  volumes:
    - /srv/docker/octobercms/mysql:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=rootoctober

cms:  
  image: numnine/octobercms
  links:
    - mysql
  ports:
    - 10080:80
  volumes:
    - ./src:/webapp
